# .github/workflows/devsecops.yaml
name: DevSecOps Pipeline

on:
  push:
    branches: [main]

env:
  HARBOR_URL: 10.6.0.201:30002
  HARBOR_PROJECT: hackathon
  IMAGE_NAME: mon-app
  BASE_IMAGE: debian:bookworm-slim   # l'image de base depuis DockerHub

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # ── BLOC 1 : DockerHub → Pull + Analyse Vuln. ───────────────
      - name: Pull image de base depuis DockerHub
        run: docker pull ${{ env.BASE_IMAGE }}

      - name: Scan vulnérabilités sur l'image de BASE (DockerHub)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.BASE_IMAGE }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 0    # warning seulement sur la base, pas bloquant

      # ── BLOC 2 : Security/Quality + Build ────────────────────────
      - name: Build image custom (Dockerfile/App)
        run: |
          docker build \
            -t ${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            ./app

      # ── BLOC 3 : Analyse Vuln. sur le CONTAINER buildé ──────────
      - name: Scan vulnérabilités sur l'image FINALE
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          exit-code: 1    # BLOQUANT ici → image jamais poussée si vuln critique

      - name: Upload résultats scan (GitHub Security tab)
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif

      # ── BLOC 4 : Push vers REGISTRY (Harbor) ────────────────────
      - name: Login Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | \
          docker login ${{ env.HARBOR_URL }} -u ${{ secrets.HARBOR_USER }} --password-stdin

      - name: Push Image Custom → Harbor
        run: |
          docker push ${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # ── BLOC 5 : GitOps → mise à jour manifest pour ArgoCD ──────
      - name: Update manifest K8s (tag image)
        run: |
          sed -i "s|image:.*|image: ${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" k8s/deployment.yaml
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add k8s/deployment.yaml
          git commit -m "ci: deploy ${{ github.sha }}"
          git push
